[tox]
envlist = py38
skipsdist = True
tox_pip_extensions_ext_venv_update = true 

[testenv]
deps =
    pytest
    coverage
    cmake
    pytest-cov
    boto3
    pytest-env
    moto[s3,ses,glue,secretsmanager]
    s3fs
    pyspark
    awsglue-local
    awswrangler
commands = pytest --cov=./ --cov-report=xml --cov-config=tox.ini
 
[coverage:run]


#[tox]
#envlist = py36, py37, py38

#[testenv]
#deps = pytest
#commands = pytest
